object Versions {
    const val kotlin = "1.3.72"
    const val core_ktx= "1.3.1"
    const val appcompat= "1.2.0"
    const val constraintlayout= "1.1.3"
    const val junit= "4.12"
    const val androidx_junit= "1.1.1"
    const val espresso_core= "3.2.0"
    const val nav_version = "2.3.0"
    const val hilt = "2.28-alpha"
    const val converter_gson = "2.9.0"
    const val logging_interceptor = "4.7.2"
    const val adapter_rxjava2 = "2.6.3"
    const val rxkotlin = "2.2.0"
}